[project]
name = "economics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ace-tools>=0.0",
    "ipykernel==6.29.5",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
]
